# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8aaa9ba60747c314234bd81dade64b337f426697f38525d56403987c38f2bc1c24717b5b127681edc814afd6e5f82091ca97e2b042927df556a4a8102a2c2494

test:
  secret_key_base: 27a145d56adc3172caf25bd727e4c5a8bb3c8fabf0a719afe860ec506069826e134353fa087f48691493cb6944fbf45b34a1d1464fa6459f808090887a440fbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
